device: cuda  # auto | cpu | cuda | mps

default_model: convnext
models:
  convnext:
    model_name: convnextv2_base.fcmae_ft_in22k_in1k
    img_size: 288
    mlflow:
      enabled: true
      stage: Production
  swin_base:
    model_name: swin_base_patch4_window7_224.ms_in22k
    img_size: 224
    mlflow:
      enabled: true
      stage: Production

allowed_origins:
  - https://medicinal-plant-one.vercel.app
